files:
  include: '**/*.scss'
  ignore:
    - 'sass/vendor/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  one-declaration-per-line: 0
  no-warn: 1
  no-debug: 1
  no-ids: 3
  no-important: 1
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-invalid-hex: 1
  hex-notation:
    - 3
    -
      style: lowercase
  hex-length:
    - 3
    -
      style: long
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3
  space-before-colon: 1
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  url-quotes: 1
  variable-name-format:
  - 1
  - allow-leading-underscore: false
    convention: hyphenatedlowercase
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
