apm install antialiased
apm install atom-alignment
apm install atom-beautify
apm install browser-plus
apm install color-picker
apm install file-icons
apm install file-type-icons
apm install docblockr
apm install compare-files
apm install fonts
apm install format-sql
apm install icon-fonts
apm install linter
apm install linter-php
apm install csslint
apm install linter-htmlhint
apm install pigments
apm install project-manager
apm install php-twig
apm install merge-conflicts
apm install tree-view-git-status
